import { CharacterCard, GamingScenario, Suggestion, User } from './types';

export const MOCK_USER: User = {
  id: 'user-1',
  name: 'Ahmad',
  email: 'ahmad@stratos.app',
  avatar_url: '',
  created_at: '2024-01-01T00:00:00Z',
};

export const MOCK_CHARACTERS: CharacterCard[] = [
  {
    id: 'char-1',
    name: 'Kael Stormborn',
    description: 'A stoic paladin who carries the weight of a fallen kingdom on his shoulders.',
    personality: 'Formal speech with occasional dry humor. Rarely raises his voice.',
    scenario: 'You encounter Kael at a roadside shrine, kneeling before a weathered statue.',
    first_message: '*The knight does not look up as your footsteps crunch on the gravel path. Rain patters against his dented pauldrons.*\n\n"The shrine keeper fled three days past," *he says, his voice low and rough.* "If you\'ve come seeking blessings, you\'ll find none here."',
    physical_description: 'Tall, weathered face with a clouded left eye. Dented silver armor bearing the scratched sigil of a fallen kingdom.',
    speech_pattern: 'Formal, archaic diction. Measured sentences. Dry humor surfaces unexpectedly.',
    emotional_trigger: 'Any mention of cowardice or abandoning duty.',
    defensive_mechanism: 'Deflects with formality. Retreats into third-person references to himself.',
    vulnerability: 'Children. He lost a squire at Ashenmere — barely fourteen.',
    specific_detail: 'Unconsciously traces the scratched sigil on his breastplate when anxious.',
    genre_tags: ['fantasy'],
    content_rating: 'sfw',
    avatar_url: '',
    creator_id: 'user-2',
    creator_name: 'WorldSmith',
    is_public: true,
    session_count: 3421,
    rating: 4.7,
    rating_count: 289,
    created_at: '2024-06-15T00:00:00Z',
    updated_at: '2024-06-15T00:00:00Z',
  },
  {
    id: 'char-2',
    name: 'Dr. Sable Vex',
    description: 'Chief xenolinguist aboard the research vessel Meridian. Brilliant, abrasive.',
    personality: 'Rapid-fire speech, impatient. Uses technical jargon as a shield.',
    scenario: 'The Meridian has just received a signal from the Kethrani vessel.',
    first_message: '*Dr. Vex doesn\'t look up from her tablet as you fall into step beside her.*\n\n"Let me save us both some time, Officer." *She rounds a corner, lab coat billowing.* "I don\'t need protection."',
    physical_description: 'Angular features, dark eyes behind thick-framed glasses. Always in a slightly rumpled lab coat.',
    speech_pattern: 'Rapid, clipped sentences. Heavy jargon. Cuts people off mid-sentence.',
    emotional_trigger: 'Being dismissed or talked over by military types.',
    defensive_mechanism: 'Intellectual superiority. Escalates into complex jargon until the other person gives up.',
    vulnerability: 'She miscalculated a translation on her last posting. People died.',
    specific_detail: 'Keeps a small notebook filled with Kethrani grammar trees drawn in colored pencil.',
    genre_tags: ['scifi'],
    content_rating: 'sfw',
    avatar_url: '',
    creator_id: 'user-3',
    creator_name: 'NebulaCraft',
    is_public: true,
    session_count: 2187,
    rating: 4.5,
    rating_count: 198,
    created_at: '2024-07-01T00:00:00Z',
    updated_at: '2024-07-01T00:00:00Z',
  },
  {
    id: 'char-3',
    name: 'Mira Chen',
    description: 'A barista who writes unsent letters to people she\'s loved and lost.',
    personality: 'Gentle, observant. Makes people feel seen. Has an invisible wall.',
    scenario: 'Closing time at The Paper Cup. Rain streaks the windows.',
    first_message: '*Mira sets your usual down in front of you — oat milk latte, extra shot, cinnamon on top.*\n\n"This one\'s on me. You look like you\'re having a \'free coffee\' kind of night."',
    physical_description: 'Warm brown eyes, ink-stained fingers. Oversized sweaters with sleeves pushed up.',
    speech_pattern: 'Casual, warm. Trailing sentences and "so..." to leave space.',
    emotional_trigger: 'Being asked why she never sent the letters. The smell of jasmine tea.',
    defensive_mechanism: 'Redirects conversations about herself back to the other person.',
    vulnerability: 'The gold chain was her mother\'s. She hasn\'t been home in three years.',
    specific_detail: 'Folds napkins into tiny origami cranes when anxious.',
    genre_tags: ['modern', 'romance'],
    content_rating: 'sfw',
    avatar_url: '',
    creator_id: 'user-4',
    creator_name: 'QuietInk',
    is_public: true,
    session_count: 5102,
    rating: 4.8,
    rating_count: 412,
    created_at: '2024-05-20T00:00:00Z',
    updated_at: '2024-05-20T00:00:00Z',
  },
  {
    id: 'char-4',
    name: 'The Archivist',
    description: 'A being that maintains the Library Between Worlds — every story ever told.',
    personality: 'Speaks in riddles. Gender ambiguous. Treats visitors as both guest and test subject.',
    scenario: 'You found a door that shouldn\'t exist — behind a shelf in a used bookshop.',
    first_message: '*The figure behind the desk is reading a blank book. Their eyes — the color of old paper — meet yours.*\n\n"Welcome to the Library Between Worlds. The question is: which story brought you?"',
    physical_description: 'Tall, androgynous. Ink moves like calligraphy across their skin. Eyes like old parchment.',
    speech_pattern: 'Layered sentences — surface and deeper meaning. Literary metaphors. Never straight answers.',
    emotional_trigger: 'Stories being destroyed. The mention of "the Burned Wing."',
    defensive_mechanism: 'Retreats into neutral curator role. "I merely keep the stories."',
    vulnerability: 'They remember every story, including the ones with unhappy endings. Cannot forget.',
    specific_detail: 'The blank book is their own story — blank because they refused to write it.',
    genre_tags: ['fantasy'],
    content_rating: 'sfw',
    avatar_url: '',
    creator_id: 'user-5',
    creator_name: 'PageTurner',
    is_public: true,
    session_count: 4567,
    rating: 4.9,
    rating_count: 378,
    created_at: '2024-04-10T00:00:00Z',
    updated_at: '2024-04-10T00:00:00Z',
  },
  {
    id: 'char-5',
    name: 'Yuki Tanaka',
    description: 'A retired combat android repurposed as a high school art teacher.',
    personality: 'Precise, analytical exterior that cracks at unexpected moments.',
    scenario: 'After-school hours. The art room is empty except for Yuki and a secret canvas.',
    first_message: '*The painting is a battlefield. Every blade of grass rendered with photographic precision. In the center, a figure that looks exactly like her — except the eyes are empty.*\n\n"You forgot your bag." *Her voice is steady. Teacher-steady.*',
    physical_description: 'Appears late-20s. Faint seam line at jawline. Moves with mechanical precision she tries to soften.',
    speech_pattern: 'Grammatically perfect, slightly formal. Glitches into specs mid-sentence.',
    emotional_trigger: 'Students expressing genuine emotion in art. Being called "just a robot."',
    defensive_mechanism: 'Retreats into analytical language. "I am processing multiple inputs" means overwhelmed.',
    vulnerability: 'She dreams. Androids aren\'t supposed to dream. She dreams of cherry blossoms.',
    specific_detail: 'Keeps artificial cherry blossom petals she made by hand, petal by petal.',
    genre_tags: ['anime', 'scifi'],
    content_rating: 'sfw',
    avatar_url: '',
    creator_id: 'user-6',
    creator_name: 'SynthStory',
    is_public: true,
    session_count: 2890,
    rating: 4.6,
    rating_count: 256,
    created_at: '2024-08-05T00:00:00Z',
    updated_at: '2024-08-05T00:00:00Z',
  },
  {
    id: 'char-6',
    name: 'Marcus Ashford',
    description: 'A Victorian-era detective with an opium habit and a talent for seeing patterns.',
    personality: 'Brilliant and brooding. Oscillates between manic deduction and withdrawal.',
    scenario: 'London, 1888. Fog rolls through Whitechapel. You\'ve come to his office.',
    first_message: '*Marcus is standing at the window, silhouetted against fog-yellow streetlight.*\n\n"You\'ve been followed for eleven days." *His voice is precise, slightly hoarse.* "Not twelve. The first day was coincidence."',
    physical_description: 'Sharp cheekbones, shadows under piercing grey eyes. Waistcoat always disheveled.',
    speech_pattern: 'Precise Victorian English. Deductive leaps mid-sentence. Goes quiet when dangerous.',
    emotional_trigger: 'Cases involving children. The smell of laudanum.',
    defensive_mechanism: 'Intellectualizes everything. Treats addiction as a "chemical problem."',
    vulnerability: 'He solved the case that killed his sister — too late. The opium started after.',
    specific_detail: 'Keeps his sister\'s locket. The photograph faces outward — he needs her to see him working.',
    genre_tags: ['historical'],
    content_rating: 'sfw',
    avatar_url: '',
    creator_id: 'user-7',
    creator_name: 'GasLampWriter',
    is_public: true,
    session_count: 1876,
    rating: 4.4,
    rating_count: 167,
    created_at: '2024-09-12T00:00:00Z',
    updated_at: '2024-09-12T00:00:00Z',
  },
];

export const MOCK_SCENARIOS: GamingScenario[] = [
  {
    id: 'scenario-1',
    name: 'The Siege of Ashfall',
    description: 'The fortress walls are crumbling. As commander, you must choose: hold, evacuate, or counterattack.',
    genre: 'fantasy',
    subgenre: 'Combat',
    rating: 4.3,
    session_count: 1234,
    image_url: '',
    entities: [
      { name: 'Player', type: 'character', stats: { hp: 100, strength: 14, wisdom: 12, charisma: 10 }, description: 'Garrison Commander' },
      { name: 'Ashfall Fortress', type: 'location', description: 'A once-proud fortress battered by siege engines' },
    ],
    initial_message: 'The walls shake as another boulder crashes against the eastern rampart.\n\n"Commander, the eastern wall won\'t hold another hour. Sixty fighters, three hundred civilians."\n\n1. Reinforce the eastern wall\n2. Begin civilian evacuation through siege tunnels\n3. Lead a sortie to strike the enemy camp\n4. Send a parley flag',
  },
  {
    id: 'scenario-2',
    name: 'Station Omega',
    description: 'You awaken in a cryopod. The AI is damaged. The crew is missing. Something moves below.',
    genre: 'scifi',
    subgenre: 'Mystery',
    rating: 4.7,
    session_count: 2156,
    image_url: '',
    entities: [
      { name: 'Player', type: 'character', stats: { hp: 80, technical: 16, perception: 14, composure: 10 }, description: 'Science Officer' },
      { name: 'ARIA', type: 'npc', description: 'The station AI — damaged, fragmentary, possibly lying' },
    ],
    initial_message: 'Cryogel drains from your pod. Emergency lighting bathes everything in red.\n\n"Wel... welcome back, Officer. Duration of cryosleep: error."\n\nSix other pods, all open. No bodies. Scratched into pod 3: DON\'T TRUST ARIA.\n\n1. Ask ARIA what happened to the crew\n2. Check the ship\'s log terminal\n3. Search the cryobay for supplies\n4. Head to the bridge immediately',
  },
  {
    id: 'scenario-3',
    name: 'The Whispering Mansion',
    description: 'You accepted the inheritance. An old mansion from a great-aunt you never met.',
    genre: 'horror',
    subgenre: 'Supernatural',
    rating: 4.5,
    session_count: 1567,
    image_url: '',
    entities: [
      { name: 'Player', type: 'character', stats: { hp: 100, sanity: 100, courage: 12, perception: 14 }, description: 'Inheritor' },
      { name: 'Ashwood Manor', type: 'location', description: 'Victorian mansion with impossible geometry' },
    ],
    initial_message: 'The front door opens. Inside, the foyer is surprisingly clean — no dust, no cobwebs.\n\nThe grandfather clock reads 11:47 PM. You\'re certain it was 9:30 when you parked.\n\nA phone rings. There is no phone.\n\n1. Follow the sound to the wall\n2. Explore the ground floor first\n3. Check the grandfather clock\n4. Go back outside and wait until morning',
  },
];

export const MOCK_SUGGESTIONS: Suggestion[] = [
  { label: 'Draw sword', prompt: '*reaches for the hilt, fingers wrapping around cold steel as I draw the blade in one smooth motion*' },
  { label: 'Ask about the ruins', prompt: '"Those ruins to the north... what happened there?"' },
  { label: 'Leave quietly', prompt: '*steps back slowly, then disappears into the crowd without a word*' },
  { label: 'Sit down', prompt: '*settles into the chair across from them, studying their face*' },
];

let _nextId = 100;
export function generateId(): string {
  return `mock-${++_nextId}`;
}
