"""Scenario file structure templates and generators.

Defines the canonical folder structure for scenarios and provides
helpers to create NPC folders, item files, and full scenario skeletons.
"""

import os
import json
import logging

logger = logging.getLogger(__name__)

# The canonical folder structure for every scenario
SCENARIO_STRUCTURE = {
    "_sources": {},  # Raw wiki/API responses cached here (for Canon Import)
    "world": {
        "setting.md": None,        # Generated from LLM
        "rules.md": None,          # Generated from LLM
        "locations": {
            "_index.json": {"locations": []},
        },
        "factions": {
            "_index.json": {"factions": []},
        },
        "lore": {},
        "mechanics": {
            "combat.md": None,     # Generated from LLM
            "skills.md": None,     # Generated from LLM
            "crafting.md": None,   # Generated or empty
            "economy.md": None,    # Generated or empty
        },
    },
    "characters": {
        "_roster.json": {"npcs": [], "player": {"id": "player", "directory": "characters/player/"}},
        "player": {
            "identity.md": "# Player Character\n\n(Generated on first interaction)",
            "stats.md": None,      # Generated from LLM
            "equipment.md": None,  # Generated from LLM
            "inventory.md": "## Equipped\n(see equipment.md)\n\n## Backpack\n(empty)",
            "skills.md": "## Learned Skills\n(none yet)\n\n## Available to Learn\n(determined by class)",
            "quests.md": "## Active Quests\n(none yet)\n\n## Available\n(check Quest Board)\n\n## Completed\n(none yet)",
            "journal.md": "## Player Journal\n\nDiscoveries and notes will appear here as you explore.",
        },
        "npcs": {},
    },
    "scenes": {
        "current.md": None,        # Generated from LLM
        "history": {},
        "encounters": {},
    },
    "items": {
        "_catalog.json": {"items": []},
        "weapons": {},
        "armor": {},
        "consumables": {},
        "key_items": {},
    },
    "conversation_log": {},
}


def get_scenario_base_path(data_dir, profile_id):
    """Return the base path for a profile's scenarios."""
    return os.path.join(data_dir, "users", str(profile_id), "context", "gaming", "scenarios")


def create_scenario_skeleton(base_path, scenario_name):
    """Create the empty folder structure for a new scenario.

    Returns the scenario root path.
    """
    scenario_path = os.path.join(base_path, scenario_name)

    def _create_recursive(path, structure):
        os.makedirs(path, exist_ok=True)
        for name, content in structure.items():
            full_path = os.path.join(path, name)
            if isinstance(content, dict):
                if name.endswith('.json'):
                    with open(full_path, 'w') as f:
                        json.dump(content, f, indent=2)
                else:
                    _create_recursive(full_path, content)
            elif isinstance(content, str):
                with open(full_path, 'w') as f:
                    f.write(content)
            # None means "will be generated by LLM"

    _create_recursive(scenario_path, SCENARIO_STRUCTURE)

    # Create _index.json at root
    index = {
        "name": scenario_name,
        "display_name": scenario_name.replace('_', ' '),
        "genre": "",
        "created": "",
        "current_scene": "scenes/current.md",
        "current_location": "",
        "active_npcs_in_scene": [],
        "rp_mode": "gm",
        "active_npc": None,
        "player_character": "characters/player/",
        "session_count": 0,
        "total_exchanges": 0,
    }
    with open(os.path.join(scenario_path, '_index.json'), 'w') as f:
        json.dump(index, f, indent=2)

    return scenario_path


def get_npc_template():
    """Return the file structure for a new NPC folder."""
    return {
        "profile.md": "",       # Name, role, personality, appearance, speaking style
        "stats.md": "",         # Combat stats if applicable
        "inventory.md": "",     # What they carry/sell
        "dialogue.md": "",      # Key lines, verbal tics, catchphrases
        "knowledge.md": "",     # What they know, rumors, secrets
        "memory.md": "## Interactions with Player\n\n(no interactions yet)\n\n## Relationship\n- Status: Unknown\n- Trust: Neutral\n",
    }


def create_npc_folder(scenario_path, npc_id, profile_data=None):
    """Create a new NPC folder with all standard files.

    Args:
        scenario_path: Root of the scenario
        npc_id: Filesystem-safe identifier (e.g., 'alice', 'klein')
        profile_data: Optional dict with keys matching file names (without .md)
    """
    npc_path = os.path.join(scenario_path, 'characters', 'npcs', npc_id)
    os.makedirs(npc_path, exist_ok=True)

    template = get_npc_template()
    for filename, default_content in template.items():
        filepath = os.path.join(npc_path, filename)
        if not os.path.exists(filepath):
            content = default_content
            if profile_data:
                key = filename.replace('.md', '')
                if key in profile_data and profile_data[key]:
                    content = profile_data[key]
            with open(filepath, 'w') as f:
                f.write(content)

    # Update _roster.json
    roster_path = os.path.join(scenario_path, 'characters', '_roster.json')
    try:
        with open(roster_path, 'r') as f:
            roster = json.load(f)
    except Exception:
        roster = {"npcs": [], "player": {"id": "player", "directory": "characters/player/"}}

    existing_ids = [n['id'] for n in roster['npcs']]
    if npc_id not in existing_ids:
        display_name = npc_id.replace('_', ' ').title()
        if profile_data and profile_data.get('name'):
            display_name = profile_data['name']

        roster['npcs'].append({
            "id": npc_id,
            "name": display_name,
            "short": profile_data.get('short', '') if profile_data else '',
            "location": profile_data.get('location', '') if profile_data else '',
            "keywords": profile_data.get('keywords', [npc_id]) if profile_data else [npc_id],
            "status": "active",
            "can_fight": profile_data.get('can_fight', False) if profile_data else False,
            "can_trade": profile_data.get('can_trade', False) if profile_data else False,
        })

        with open(roster_path, 'w') as f:
            json.dump(roster, f, indent=2)

    return npc_path


def create_item_file(scenario_path, item_data):
    """Create an item file and update the catalog.

    item_data: {
        "id": "iron_blade",
        "name": "Iron Blade",
        "type": "weapon", "subtype": "sword",
        "rarity": "common",
        "keywords": ["iron", "blade", "sword"],
        "description": "A sturdy iron sword..."
    }
    """
    type_folder_map = {
        "weapon": "weapons",
        "armor": "armor",
        "consumable": "consumables",
        "key_item": "key_items",
    }

    folder = type_folder_map.get(item_data.get('type', ''), 'weapons')
    item_dir = os.path.join(scenario_path, 'items', folder)
    os.makedirs(item_dir, exist_ok=True)

    safe_id = os.path.basename(item_data['id']).replace('..', '_')
    item_path = os.path.join(item_dir, f"{safe_id}.md")
    with open(item_path, 'w') as f:
        f.write(item_data.get('description', f"# {item_data['name']}\n\n(No description yet)"))

    # Update _catalog.json
    catalog_path = os.path.join(scenario_path, 'items', '_catalog.json')
    try:
        with open(catalog_path, 'r') as f:
            catalog = json.load(f)
    except Exception:
        catalog = {"items": []}

    existing_ids = [i['id'] for i in catalog['items']]
    if item_data['id'] not in existing_ids:
        catalog['items'].append({
            "id": item_data['id'],
            "name": item_data['name'],
            "type": item_data.get('type', 'weapon'),
            "subtype": item_data.get('subtype', ''),
            "rarity": item_data.get('rarity', 'common'),
            "keywords": item_data.get('keywords', [item_data['id']]),
            "file": f"items/{folder}/{item_data['id']}.md",
        })
        with open(catalog_path, 'w') as f:
            json.dump(catalog, f, indent=2)

    return item_path


def migrate_old_scenario(scenario_path):
    """Convert old single-file scenario (state.md + world.md) to new multi-folder structure.

    Detection: world.md exists at root AND world/ directory does NOT exist.
    Called automatically when a scenario is loaded and old format is detected.
    """
    world_md_file = os.path.join(scenario_path, 'world.md')
    world_dir = os.path.join(scenario_path, 'world')
    if not os.path.exists(world_md_file) or os.path.isdir(world_dir):
        return False  # Already migrated or not old format

    logger.info(f"Migrating old scenario: {scenario_path}")

    # 1. Read old content
    old_world = ''
    try:
        with open(world_md_file, 'r') as f:
            old_world = f.read()
    except Exception:
        pass

    old_state = ''
    state_md_file = os.path.join(scenario_path, 'state.md')
    try:
        with open(state_md_file, 'r') as f:
            old_state = f.read()
    except Exception:
        pass

    # 2. Create new folder structure in-place
    scenario_name = os.path.basename(scenario_path)
    for name, content in SCENARIO_STRUCTURE.items():
        full_path = os.path.join(scenario_path, name)
        if isinstance(content, dict):
            if name.endswith('.json'):
                if not os.path.exists(full_path):
                    with open(full_path, 'w') as f:
                        json.dump(content, f, indent=2)
            else:
                _create_structure_recursive(full_path, content)
        elif isinstance(content, str) and not os.path.exists(full_path):
            with open(full_path, 'w') as f:
                f.write(content)

    # 3. Move old content to new locations
    if old_world:
        setting_path = os.path.join(scenario_path, 'world', 'setting.md')
        with open(setting_path, 'w') as f:
            f.write(old_world)

    if old_state:
        scene_path = os.path.join(scenario_path, 'scenes', 'current.md')
        with open(scene_path, 'w') as f:
            f.write(old_state)

    # 4. Create _index.json if missing
    index_path = os.path.join(scenario_path, '_index.json')
    if not os.path.exists(index_path):
        index = {
            "name": scenario_name,
            "display_name": scenario_name.replace('_', ' '),
            "genre": "",
            "created": "",
            "current_scene": "scenes/current.md",
            "current_location": "",
            "active_npcs_in_scene": [],
            "rp_mode": "gm",
            "active_npc": None,
            "player_character": "characters/player/",
            "session_count": 0,
            "total_exchanges": 0,
        }
        with open(index_path, 'w') as f:
            json.dump(index, f, indent=2)

    # 5. Rename old files (don't delete — safety)
    try:
        os.rename(world_md_file, world_md_file + '.old')
    except Exception:
        pass
    if os.path.exists(state_md_file):
        try:
            os.rename(state_md_file, state_md_file + '.old')
        except Exception:
            pass

    logger.info(f"Migration complete: {scenario_path}")
    return True


def _create_structure_recursive(path, structure):
    """Helper to create nested folder structure."""
    os.makedirs(path, exist_ok=True)
    for name, content in structure.items():
        full_path = os.path.join(path, name)
        if isinstance(content, dict):
            if name.endswith('.json'):
                if not os.path.exists(full_path):
                    with open(full_path, 'w') as f:
                        json.dump(content, f, indent=2)
            else:
                _create_structure_recursive(full_path, content)
        elif isinstance(content, str) and not os.path.exists(full_path):
            with open(full_path, 'w') as f:
                f.write(content)
